using System;
using System.Net;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using FluentAssertions;
using Microsoft.Extensions.Options;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace OpenClaw.Core.Tests;

/// <summary>
/// Unit tests for the fail-closed local Stage-0 <c>UpdateEventTimesAsync</c> (issue #128).
/// Kept in a separate file from <see cref="HostAdapterHttpClientTests"/> to hold each test
/// file under the 500-line cap; reuses the shared <see cref="FakeHttpHandler"/> defined
/// alongside <see cref="HostAdapterHttpClientTests"/>. The local backend has no
/// calendar-write route, so the call returns a non-retryable <c>NOT_SUPPORTED</c> envelope
/// and performs no HTTP I/O.
/// </summary>
[TestClass]
public sealed class HostAdapterHttpClientRescheduleTests
{
    private static readonly DateTimeOffset NewStart = new(2026, 7, 9, 14, 0, 0, TimeSpan.Zero);
    private static readonly DateTimeOffset NewEnd = new(2026, 7, 9, 14, 30, 0, TimeSpan.Zero);

    private static HostAdapterHttpClient BuildClient(FakeHttpHandler handler)
    {
        var opts = new OpenClawOptions();
        opts.HostAdapter.TokenFile = "/run/openclaw/hostadapter.token";
        opts.HostAdapter.BaseUrl = "http://localhost:4319/";
        var httpClient = new HttpClient(handler)
        {
            BaseAddress = new Uri("http://localhost:4319/"),
        };
        return new HostAdapterHttpClient(httpClient, Options.Create(opts))
        {
            // A token reader that throws proves no token acquisition occurs on this path.
            TokenReader = (_, _) =>
                throw new AssertFailedException(
                    "The fail-closed reschedule path must not read a token."
                ),
        };
    }

    [TestMethod]
    public async Task UpdateEventTimes_LocalBackend_ReturnsNotSupportedWithoutHttpIo()
    {
        var handlerInvocations = 0;
        var handler = new FakeHttpHandler(_ =>
        {
            handlerInvocations++;
            return Task.FromResult(new HttpResponseMessage(HttpStatusCode.OK));
        });
        var client = BuildClient(handler);

        var result = await client.UpdateEventTimesAsync(
            "evt-1",
            NewStart,
            NewEnd,
            requestId: "req-local"
        );

        result.Ok.Should().BeFalse();
        result.Data.Should().BeNull();
        result.Error.Should().NotBeNull();
        result.Error!.Code.Should().Be("NOT_SUPPORTED");
        result.Error.Retryable.Should().BeFalse();
        result.Meta.RequestId.Should().Be("req-local");
        handlerInvocations.Should().Be(0, "the local backend performs no HTTP I/O on this path");
    }

    [TestMethod]
    public async Task UpdateEventTimes_NullRequestId_SelfGeneratesRequestIdStillNotSupported()
    {
        var handlerInvocations = 0;
        var handler = new FakeHttpHandler(_ =>
        {
            handlerInvocations++;
            return Task.FromResult(new HttpResponseMessage(HttpStatusCode.OK));
        });
        var client = BuildClient(handler);

        var result = await client.UpdateEventTimesAsync("evt-1", NewStart, NewEnd);

        result.Ok.Should().BeFalse();
        result.Error!.Code.Should().Be("NOT_SUPPORTED");
        result
            .Meta.RequestId.Should()
            .NotBeNullOrWhiteSpace("a null request id is self-generated by the adapter");
        handlerInvocations.Should().Be(0);
    }
}
